// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=usecase_mock_test.go -package=web
//

// Package web is a generated GoMock package.
package web

import (
	context "context"
	reflect "reflect"

	web "github.com/Role1776/mcp-retrieval/app/internal/dto/web"
	gomock "go.uber.org/mock/gomock"
)

// Mockusecase is a mock of usecase interface.
type Mockusecase struct {
	ctrl     *gomock.Controller
	recorder *MockusecaseMockRecorder
	isgomock struct{}
}

// MockusecaseMockRecorder is the mock recorder for Mockusecase.
type MockusecaseMockRecorder struct {
	mock *Mockusecase
}

// NewMockusecase creates a new mock instance.
func NewMockusecase(ctrl *gomock.Controller) *Mockusecase {
	mock := &Mockusecase{ctrl: ctrl}
	mock.recorder = &MockusecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockusecase) EXPECT() *MockusecaseMockRecorder {
	return m.recorder
}

// ScrapePages mocks base method.
func (m *Mockusecase) ScrapePages(ctx context.Context, req web.ScrapeRequest) (web.ScrapeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScrapePages", ctx, req)
	ret0, _ := ret[0].(web.ScrapeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScrapePages indicates an expected call of ScrapePages.
func (mr *MockusecaseMockRecorder) ScrapePages(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScrapePages", reflect.TypeOf((*Mockusecase)(nil).ScrapePages), ctx, req)
}

// SearchImages mocks base method.
func (m *Mockusecase) SearchImages(ctx context.Context, req web.ImagesSearchRequest) (web.ImagesSearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchImages", ctx, req)
	ret0, _ := ret[0].(web.ImagesSearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchImages indicates an expected call of SearchImages.
func (mr *MockusecaseMockRecorder) SearchImages(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchImages", reflect.TypeOf((*Mockusecase)(nil).SearchImages), ctx, req)
}

// SearchSnippets mocks base method.
func (m *Mockusecase) SearchSnippets(ctx context.Context, req web.SearchRequest) (web.SearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchSnippets", ctx, req)
	ret0, _ := ret[0].(web.SearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchSnippets indicates an expected call of SearchSnippets.
func (mr *MockusecaseMockRecorder) SearchSnippets(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchSnippets", reflect.TypeOf((*Mockusecase)(nil).SearchSnippets), ctx, req)
}
